// Tournament Engine — Format-agnostic bracket and DAG management.
// Pure functions operating on tournament objects. No Firebase dependency.

/**
 * Generate a default team name from player names.
 * First 2 chars of each name, capitalized, joined by " & ".
 * e.g. ["alice", "bob"] → "Al & Bo"
 */
export function generateTeamName(players) {
  if (!players || players.length === 0) return 'Team';
  return players.map(p => {
    const t = p.trim();
    if (t.length === 0) return '??';
    if (t.length === 1) return t.toUpperCase();
    return t.charAt(0).toUpperCase() + t.charAt(1).toLowerCase();
  }).join(' & ');
}

/**
 * Create a TournamentGame object with sensible defaults.
 */
export function createGame({ id, round, roundName, position, bracket = 'main', slots, isBye = false }) {
  return {
    id, round, roundName, position, bracket, slots,
    teams: [{ teamId: null, name: null }, { teamId: null, name: null }],
    isBye,
    status: 'waiting',
    result: null,
  };
}

export function getGameById(tournament, gameId) {
  return tournament.games.find(g => g.id === gameId) || null;
}

/**
 * Get all games that are ready to be played (status='ready', not a bye).
 */
export function getReadyGames(tournament) {
  return tournament.games.filter(g => g.status === 'ready' && !g.isBye);
}

/**
 * Get the next game to play according to the default play order.
 */
export function getNextDefaultGame(tournament) {
  for (const gameId of tournament.defaultGameOrder) {
    const game = getGameById(tournament, gameId);
    if (game && game.status === 'ready' && !game.isBye) return game;
  }
  return null;
}

/**
 * Validate tournament setup before lock-in.
 */
export function validateTournamentSetup(teams, format, config) {
  const errors = [];
  if (!teams || teams.length < 2) errors.push('At least 2 teams are required');
  if (teams && teams.length > 30) errors.push('Maximum 30 teams allowed');

  const validFormats = ['single_elim', 'double_elim', 'swiss', 'round_robin'];
  if (!validFormats.includes(format)) {
    errors.push(`Invalid format: ${format}. Must be one of: ${validFormats.join(', ')}`);
  }

  if (teams) {
    for (const team of teams) {
      if (!team.players || team.players.length === 0) {
        errors.push(`Team "${team.name || team.id}" has no players`);
      }
      if (team.players && team.players.length > 2) {
        errors.push(`Team "${team.name || team.id}" has more than 2 players`);
      }
    }
    const allPlayers = teams.flatMap(t => t.players || []);
    const seen = new Set();
    for (const player of allPlayers) {
      if (seen.has(player)) errors.push(`Player "${player}" appears in multiple teams`);
      seen.add(player);
    }
  }

  if (format === 'swiss' && config) {
    if (config.swissRounds != null && config.swissRounds < 1) {
      errors.push('Swiss rounds must be at least 1');
    }
  }

  return { valid: errors.length === 0, errors };
}

/**
 * Initialize bracket after games have been generated by a format generator.
 * Resolves seed-based slots to actual teams, detects byes, auto-completes them,
 * and cascades to fill dependent games.
 */
export function initializeBracket(tournament) {
  const seedMap = new Map();
  for (const team of tournament.teams) {
    seedMap.set(team.seed, team);
  }

  // Resolve seed-based slots to actual teams
  for (const game of tournament.games) {
    for (let i = 0; i < 2; i++) {
      const slot = game.slots[i];
      if (slot.seed != null) {
        const team = seedMap.get(slot.seed);
        if (team) {
          game.teams[i] = { teamId: team.id, name: team.name };
        }
        // else: seed beyond team count → stays null (bye)
      }
    }
  }

  // Detect byes: seed-based games where exactly one team resolved
  for (const game of tournament.games) {
    const hasSeedSlots = game.slots.some(s => s.seed != null);
    if (!hasSeedSlots) continue;

    const t0 = game.teams[0]?.teamId != null;
    const t1 = game.teams[1]?.teamId != null;

    if (t0 && t1) {
      game.status = 'ready';
    } else if (t0 && !t1) {
      game.isBye = true;
      game.status = 'completed';
      game.result = { winner: 0, matchId: null, score: [0, 0] };
    } else if (!t0 && t1) {
      game.isBye = true;
      game.status = 'completed';
      game.result = { winner: 1, matchId: null, score: [0, 0] };
    }
    // Both null shouldn't happen with valid bracket generation
  }

  // Cascade all completed byes
  const completedIds = tournament.games
    .filter(g => g.status === 'completed')
    .map(g => g.id);

  if (completedIds.length > 0) {
    cascadeResults(tournament, completedIds);
  }

  return tournament;
}

/**
 * Complete a game: set result, cascade to dependents, check tournament completion.
 * Returns array of game IDs that became newly ready.
 */
export function completeGame(tournament, gameId, winnerIndex, matchId, score) {
  const game = getGameById(tournament, gameId);
  if (!game) throw new Error(`Game "${gameId}" not found`);
  if (game.status === 'completed') throw new Error(`Game "${gameId}" is already completed`);
  if (game.status !== 'ready') throw new Error(`Game "${gameId}" is not ready (status: ${game.status})`);
  if (winnerIndex !== 0 && winnerIndex !== 1) throw new Error('winnerIndex must be 0 or 1');

  game.status = 'completed';
  game.result = { winner: winnerIndex, matchId, score: score || [0, 0] };

  const newlyReady = cascadeResults(tournament, [gameId]);

  if (isTournamentComplete(tournament)) {
    tournament.state = 'completed';
    tournament.completedAt = Date.now();
  }

  return newlyReady;
}

/**
 * Check if the tournament is complete.
 */
export function isTournamentComplete(tournament) {
  if (tournament.format === 'swiss') {
    const expectedRounds = tournament.config?.swissRounds ||
      Math.ceil(Math.log2(tournament.teams.length));
    const maxRound = Math.max(0, ...tournament.games.map(g => g.round));
    if (maxRound < expectedRounds) return false;
  }

  return tournament.games
    .filter(g => !g.isBye)
    .every(g => g.status === 'completed');
}

/**
 * Check if a specific Swiss round is complete.
 */
export function isSwissRoundComplete(tournament, roundNumber) {
  const roundGames = tournament.games.filter(g => g.round === roundNumber);
  if (roundGames.length === 0) return false;
  return roundGames.every(g => g.status === 'completed' || g.isBye);
}

/**
 * Get the current (latest) Swiss round number.
 */
export function getCurrentSwissRound(tournament) {
  if (tournament.games.length === 0) return 0;
  return Math.max(...tournament.games.map(g => g.round));
}

/**
 * Compute final rankings. Delegates to format-specific logic.
 */
export function computeFinalRankings(tournament) {
  switch (tournament.format) {
    case 'single_elim': return computeElimRankings(tournament);
    case 'double_elim': return computeDoubleElimRankings(tournament);
    case 'swiss': return computeSwissRankings(tournament);
    case 'round_robin': return computeRoundRobinRankings(tournament);
    default: return [];
  }
}

// --- Ranking helpers ---

function computeElimRankings(tournament) {
  // In single elim, rank by wins (more wins = deeper in bracket = better).
  // Teams with equal wins were eliminated in the same round → shared rank.
  const stats = buildTeamStats(tournament);

  const sorted = Array.from(stats.values()).sort((a, b) => {
    if (a.wins !== b.wins) return b.wins - a.wins;
    // Tiebreak by seed (lower seed = higher ranked entering)
    return a.seed - b.seed;
  });

  return assignRanks(sorted, (a, b) => a.wins === b.wins);
}

function computeDoubleElimRankings(tournament) {
  // For double elim, use elimination order: track when each team is eliminated
  // from the tournament (losing in LB or GF). Last eliminated = best.
  const stats = buildTeamStats(tournament);
  const eliminationOrder = []; // teamIds from first eliminated to last
  const eliminated = new Set();

  for (const gameId of tournament.defaultGameOrder) {
    const game = getGameById(tournament, gameId);
    if (!game || !game.result || game.isBye) continue;

    const loserId = game.teams[1 - game.result.winner]?.teamId;
    if (!loserId) continue;

    // In DE, elimination happens when losing in LB or GF
    if (game.bracket === 'losers' || game.bracket === 'grand_final') {
      if (!eliminated.has(loserId)) {
        eliminationOrder.push(loserId);
        eliminated.add(loserId);
      }
    }
  }

  // Champion = not eliminated
  const championId = tournament.teams.find(t => !eliminated.has(t.id))?.id;

  // Build rankings: champion first, then reverse elimination order
  const rankings = [];
  if (championId) {
    const s = stats.get(championId);
    rankings.push({ teamId: championId, teamName: s.teamName, wins: s.wins, losses: s.losses });
  }

  for (let i = eliminationOrder.length - 1; i >= 0; i--) {
    const tid = eliminationOrder[i];
    const s = stats.get(tid);
    rankings.push({ teamId: tid, teamName: s.teamName, wins: s.wins, losses: s.losses });
  }

  // Any teams not accounted for (shouldn't happen, but safety)
  for (const team of tournament.teams) {
    if (!rankings.find(r => r.teamId === team.id)) {
      const s = stats.get(team.id);
      rankings.push({ teamId: team.id, teamName: s.teamName, wins: s.wins, losses: s.losses });
    }
  }

  return rankings.map((r, i) => ({ rank: i + 1, ...r }));
}

function computeSwissRankings(tournament) {
  const stats = buildTeamStats(tournament);

  // Compute Buchholz (sum of opponents' wins)
  for (const s of stats.values()) {
    s.buchholz = s.opponents.reduce((sum, oppId) => {
      const opp = stats.get(oppId);
      return sum + (opp ? opp.wins : 0);
    }, 0);
  }

  const sorted = Array.from(stats.values()).sort((a, b) => {
    if (a.wins !== b.wins) return b.wins - a.wins;
    if (a.buchholz !== b.buchholz) return b.buchholz - a.buchholz;
    return a.seed - b.seed;
  });

  return assignRanks(sorted, (a, b) => a.wins === b.wins && a.buchholz === b.buchholz);
}

function computeRoundRobinRankings(tournament) {
  const stats = buildTeamStats(tournament);

  // Compute goal difference
  for (const game of tournament.games) {
    if (!game.result || game.isBye) continue;
    const [g0, g1] = game.result.score || [0, 0];
    const t0 = game.teams[0]?.teamId;
    const t1 = game.teams[1]?.teamId;
    if (t0) stats.get(t0).goalDiff += g0 - g1;
    if (t1) stats.get(t1).goalDiff += g1 - g0;
  }

  const sorted = Array.from(stats.values()).sort((a, b) => {
    if (a.wins !== b.wins) return b.wins - a.wins;
    if (a.goalDiff !== b.goalDiff) return b.goalDiff - a.goalDiff;
    return a.seed - b.seed;
  });

  return assignRanks(sorted, (a, b) => a.wins === b.wins && a.goalDiff === b.goalDiff);
}

function buildTeamStats(tournament) {
  const stats = new Map();
  for (const team of tournament.teams) {
    stats.set(team.id, {
      teamId: team.id,
      teamName: team.name,
      seed: team.seed,
      wins: 0,
      losses: 0,
      opponents: [],
      goalDiff: 0,
    });
  }

  for (const game of tournament.games) {
    if (!game.result || game.isBye) continue;
    const winnerId = game.teams[game.result.winner]?.teamId;
    const loserId = game.teams[1 - game.result.winner]?.teamId;
    if (winnerId && stats.has(winnerId)) stats.get(winnerId).wins++;
    if (loserId && stats.has(loserId)) stats.get(loserId).losses++;
    if (winnerId && loserId) {
      stats.get(winnerId).opponents.push(loserId);
      stats.get(loserId).opponents.push(winnerId);
    }
  }

  // Count bye wins
  for (const game of tournament.games) {
    if (!game.isBye || !game.result) continue;
    const winnerId = game.teams[game.result.winner]?.teamId;
    if (winnerId && stats.has(winnerId) && tournament.format === 'swiss') {
      stats.get(winnerId).wins++;
    }
  }

  return stats;
}

function assignRanks(sorted, isTied) {
  const result = [];
  let currentRank = 1;
  for (let i = 0; i < sorted.length; i++) {
    const rank = (i > 0 && isTied(sorted[i], sorted[i - 1])) ? result[i - 1].rank : currentRank;
    result.push({
      rank,
      teamId: sorted[i].teamId,
      teamName: sorted[i].teamName,
      wins: sorted[i].wins,
      losses: sorted[i].losses,
    });
    currentRank = i + 2;
  }
  return result;
}

// --- Cascade helper ---

/**
 * Propagate completed game results to dependent games.
 * Fills teams in dependent slots, marks games ready when both teams known.
 * Handles cascade byes (e.g., LB games sourcing from WB bye losers → null teams).
 * Returns array of non-bye game IDs that became newly ready.
 */
function cascadeResults(tournament, completedGameIds) {
  const newlyReady = [];
  const queue = [...completedGameIds];

  while (queue.length > 0) {
    const currentId = queue.shift();
    const completed = getGameById(tournament, currentId);
    if (!completed || !completed.result) continue;

    for (const game of tournament.games) {
      if (game.status === 'completed') continue;

      let changed = false;
      for (let slotIdx = 0; slotIdx < 2; slotIdx++) {
        const slot = game.slots[slotIdx];
        if (slot.sourceGameId !== currentId) continue;

        const sourceIdx = slot.sourceOutcome === 'winner'
          ? completed.result.winner
          : (1 - completed.result.winner);

        game.teams[slotIdx] = { ...completed.teams[sourceIdx] };
        changed = true;
      }

      if (!changed || game.status !== 'waiting') continue;

      // Check if all source slots are resolved (all source games completed)
      const allResolved = game.slots.every(slot => {
        if (slot.seed != null) return true;
        if (!slot.sourceGameId) return true;
        const src = getGameById(tournament, slot.sourceGameId);
        return src && src.status === 'completed';
      });
      if (!allResolved) continue;

      // Fill any slots from other completed sources that haven't been filled yet
      for (let slotIdx = 0; slotIdx < 2; slotIdx++) {
        if (game.teams[slotIdx]?.teamId != null) continue;
        const slot = game.slots[slotIdx];
        if (!slot.sourceGameId) continue;
        const src = getGameById(tournament, slot.sourceGameId);
        if (!src || !src.result) continue;
        const srcIdx = slot.sourceOutcome === 'winner'
          ? src.result.winner
          : (1 - src.result.winner);
        game.teams[slotIdx] = { ...src.teams[srcIdx] };
      }

      const t0 = game.teams[0]?.teamId != null;
      const t1 = game.teams[1]?.teamId != null;

      if (t0 && t1) {
        game.status = 'ready';
        newlyReady.push(game.id);
      } else if (t0 || t1) {
        // One null team → cascade bye
        game.isBye = true;
        game.status = 'completed';
        game.result = { winner: t0 ? 0 : 1, matchId: null, score: [0, 0] };
        queue.push(game.id);
      } else {
        // Both null → empty bye (propagates nulls further)
        game.isBye = true;
        game.status = 'completed';
        game.result = { winner: 0, matchId: null, score: [0, 0] };
        queue.push(game.id);
      }
    }
  }

  return newlyReady;
}
